var listOfQuotes = [
    {quote: 'All of time and space; everywhere and anywhere; every star that ever was. Where do you want to start?'},
    {quote: 'People assume that time is a strict progression of cause to effect, from a non-linear, non subjective viewpoint it’s more like a big ball of wibbly-wobbely timey–wimey stuff.'},
    {quote: 'Your life could depend on this. Don’t blink. Don’t even blink. Blink and you’re dead. They are fast. Faster than you can believe. Don’t turn your back, don’t look away and, don’t blink.'},
    {quote: 'Every life is a pile of good things and bad things. The good things don’t always soften the bad things but, vice versa, the bad things don’t always spoil the good things and make them unimportant.'},
    {quote: 'The universe is big, it’s vast and complicated and ridiculous and sometimes, very rarely, impossible things just happen and we call them miracles.'},
    {quote: 'Think you’ve seen it all? Think again. Outside those doors we might see anything. We could find new worlds, terrifying monsters, impossible things. And if you come with me nothing will ever be the same again.'},
    {quote: 'Didn’t anyone ever tell you? There’s one thing you never put into a trap. If you’re smart, if you value your continued existence, if you have any plans about seeing tomorrow there is one thing you never, ever put into a trap…Me.'},
    {quote: 'We all change when you think about it we’re all different people all through our lives and that’s okay, that’s good. You’ve gotta keep moving so long as you remember all the people that you used to be.'},
    {quote: 'Some people live more in 20 years than others do in 80. It’s not the time that matters it’s the person.'},
    {quote: 'You know it seems to me that there is so much more to the world than the average eye is allowed to see. I believe if you look hard, there are more wonders than you could have dreamed of.'},
    {quote: 'On the fields of Trenzalore at the fall of the eleventh; when no living creature can speak falsely or fail to answer a question will be asked a question that must be answered.'},
    {quote: 'Don’t play games with me. You just killed someone I like, that is not a safe place to stand. I’m The Doctor and you’re in the biggest library in the universe! Look me up.'},
    {quote: 'I’m being extremely clever up here and there is no one to stand around looking impressed. What’s the point in having you all?'},
    {quote: '"This is, well, she’s my Tardis, except she’s a woman, but she’s a woman and she’s my Tardis." "She’s the Tardis?" "And she’s a woman. She’s a woman she’s the Tardis." "Did you wish really hard?'},
    {quote: 'I’m old enough to know that a longer life isn’t always a better one. In the end, you just get tired; tired of the struggle, tired of losing everyone that matters to you, tired of watching everything you love turn to dust. If you live long enough, Lazarus, the only certainty left is that you’ll end up alone.'},
    {quote: '"You’re like a nine year old trying to build a motorbike in his bedroom and you never read the instructions." "I always read the instructions." "There’s a sign on my front door, you’ve been walking past it for seven hundred years, what does it say?" "That\'s not instructions" "There’s an instruction at the bottom what does it say?" "Pull to open." "Yes and what do you do?" "I push."'},
    {quote: 'I am not a good man! And I’m not a bad man. I am not a hero. And I’m definitely not a president. And, no, I’m not an officer. Do you know what I am? I am an idiot, with a box and a screwdriver.'},
    {quote: 'Could you not just let me enjoy this moment of not knowing something? I mean, it happens so rarely.'},
    {quote: 'Come on, look at me. No plan, no back up, no weapons worth a damn, oh, and something else I don’t have. Anything to lose! So, if you’re sitting up there in your silly little space ships with all your silly little guns, and you’ve got any plans on taking the Pandorica tonight, just remember who’s standing in your way! Remember every black day I ever stopped you, and then, do the smart thing! Let somebody else try first.'},
    {quote: 'I don’t look back. I can’t. But the last time I was dying I looked back on all of you. Every single one. And I was so proud.'},
    {quote: 'Legs! I’ve still got legs. Good. Arms. Hands. Ooh! Fingers. Lots of fingers. Ears; Yes. Eyes Two. Nose. And I’ve had worse. Chin. Blimey. Hair. I’m a girl. No. No. I’m not a girl and still not ginger. Something else. Something Important. I’m- I’m- Crashing! Ha ha! Geronimo!'},
    {quote: 'There’s always something to look at if you open your eyes.'},
    {quote: 'We’re so lucky. We’re still alive to see this beautiful world. Look at the sky. It’s not dark and black without character. The black is in fact deep blue. And over there! Lighter blue. And blowing through the blueness and the blackness, the winds swirling through the air. And there shining, burning, bursting through, the stars! Can you see how they roll their light? Everywhere we look, complex magic of nature blazes before our eyes.'},
    {quote: 'Sometimes knowing your own future is what enables you to change it. Especially if you’re bloody-minded, contradictory and completely unpredictable.'},
    {quote: 'Time isn’t a straight line. It’s all…bumpy-wumpy. There’s loads of boring stuff. Like Sundays and Tuesdays and Thursday afternoons. But now and then there are Saturdays. Big temporal tipping points when anything’s possible.'},
    {quote: 'The universe has to move forward. Pain and loss, they define us as much as happiness or love. Whether it’s a world or a relationship, everything has its time. And everything ends.'},
    {quote: 'When you’re a kid, they tell you it’s all “Grow up. Get a job. Get Married. Get a house. Have a kid. And that’s it.” But the truth is, the world is so much stranger than that. It’s so much darker. And so much madder. And so much better.'},
    {quote: 'Everybody know that everybody dies. And nobody knows it like the Doctor. But I do think that all the skies of all the worlds might just turn dark if he ever, for one moment accepts it.'},
    {quote: 'In my culture we believe that when you die your spirit has to climb a mountain carrying the souls of everyone you wronged in your lifetime. Imagine the weight I will have to lift. The monsters I created, the people they killed. Can you see now why I fear death? You want to hand me over, there’s no shame in that. But you won’t. We all carry our prisons with us. Mine is my past. Yours is your mortality.'},
    {quote: 'I’m usually called the Doctor. Or the caretaker. Or “Get off this planet.” Though strictly speaking that probably isn’t a name.'},
    {quote: 'When I was a child my favorite story was about a man who lived forever but whose eyes were heavy with the weight of all he had seen. A man who fell from the stars.'},
    {quote: 'It’s got my name written all over it. Well not literally but give me time and a crayon.'},
    {quote: 'Let me tell you something about the human race. You put a mysterious blue box slap-bang in the middle of the town, what do they do? Walk past it.'},
    {quote: 'Trouble’s just the bits in-between! It’s all waiting out there, Jackie. And it’s brand new to me – all those planets and creatures and horizons! I haven’t seen them yet, not with these eyes. And it is gonna be fantastic.'},
    {quote: 'I am and always will be the optimist. The hoper of far-flung hopes and dreamer of improbable dreams.'},
    {quote: 'Tea! That’s all I needed! Good cup of tea. Super-heated infusion of free-radicals and tannin. Just the thing for healing the synapses.'},
    {quote: 'What if we had ideas that could think for themselves? What if one day our dreams no longer needed us?'},
    {quote: '900 years of time and space and I’ve never met anyone who wasn’t important.'},
    {quote: 'My name, my real name, that is not the point. The name I chose is the Doctor. The name you choose, it’s like...it’s like a promise you make.'},
    {quote: 'Never ignore coincidence. Unless, of course, you’re busy. In which case, always ignore coincidence.'},
    {quote: 'I can’t save you from this. There’s nothing I can do to stop this. I stole your childhood and now I’ve lead you by the hand to your death. But the worst thing is, I knew. I knew this would happen. This is what always happens. Forget your faith in me.'},
    {quote: 'Pain is a gift. Without the capacity for pain, we can’t feel the hurt we inflict.'},
    {quote: 'The sky is full of a million, million voices saying yes, of course we’ll help. You’ve touched so many lives, saved so many people. Did you think when your time came, you’d really have to do more than just ask? You’ve decided that the universe is better off without you, but the universe doesn’t agree.'}
];

var doctorQuotes = [
    {quote: "Our lives are important - at least to us - and as we see, so we learn... Our destiny is in the stars, so let's go and search for it.", speaker: "The First Doctor"},
    {quote: "We're trying to defeat the Daleks, not start a jumble sale!", speaker: "The First Doctor"},
    {quote: "Emotions. Love. Pride. Hate. Fear. Have you no emotions sir?", speaker: "The First Doctor"},
    {quote: "I'm a citizen of the Universe and a gentleman to boot.", speaker: "The First Doctor"},
    {quote: "One day, I shall come back. Yes, I shall come back. Until then, there must be no regrets, no tears, no anxieties. Just go forward in your beliefs and prove to me that I am not mistaken in mine", speaker:"The First Doctor"},
    {quote: "We're always in trouble! Isn't this extraordinary - it follows us everywhere!", speaker: "The First Doctor"},
    {quote: "Fear itself is largely an illusion, at my age there is little left to fear, there is nothing here that can harm us.", speaker: "The First Doctor"},
    
    {quote: "Oh, yes, it could be the 20th century. England in summertime, I should say. See the rain clouds?", speaker: "The Second Doctor"},
    {quote: "An unintelligent enemy is far less dangerous than an intelligent one, Jamie. Just act stupid. Do you think you can manage that?", speaker: "The Second Doctor"},
    {quote: "They're human beings, if that's what you mean. Indulging their favorite pastime of trying to destroy each other.", speaker: "The Second Doctor"},
    {quote: "The power cable generated an electrical field and confused their tiny metal minds. You might almost say they've had a complete metal breakdown.", speaker: "The Second Doctor"},
    {quote: "I am not a student of human nature. I am a professor of a far wider academy of which human nature is merely a part.", speaker: "The Second Doctor"},
    {quote: "There are some corners of the universe which have bred the most terrible things. Things which act against everything we believe in. They must be fought!", speaker: "The Second Doctor"},
    
    {quote: "Allow me to congratulate you, sir. You have the most totally closed mind that I've ever encountered.", speaker: "The Third Doctor"},
    {quote: "Obviously the Time Lords have programmed the TARDIS always to return to Earth. It seems that I'm some sort of galactic yo-yo!", speaker: "The Third Doctor"},
    {quote: "You know Jo, I sometimes think that military intelligence is a contradiction in terms.", speaker: "The Third Doctor"},
    {quote: "Courage isn't just a matter of not being frightened, you know. It's being afraid and doing what you have to do anyway.", speaker: "The Third Doctor"},
    
    {quote: "You may be a doctor. But I'm the Doctor. The definite article, you might say.", speaker: "The Fourth Doctor"},
    {quote: "Oh please, don't call me human. Just \"Doctor\" would do very nicely, thank you.", speaker: "The Fourth Doctor"},
    {quote: "If someone who knew the future, pointed out a child to you and told you that that child would grow up totally evil, to be a ruthless dictator who would destroy millions of lives... could you then kill that child?", speaker: "The Fourth Doctor"},
    {quote: "You've no home planet, no influence, nothing! You're just a pathetic bunch of tin soldiers skulking about the galaxy in an ancient spaceship!", speaker: "The Fourth Doctor"},
    {quote: "But if I kill... wipe out a whole intelligent life-form... then I become like them. I'd be no better than the Daleks.", speaker: "The Fourth Doctor"},
    {quote: "The trouble with computers, of course, is that they're very sophisticated idiots. They do exactly what you tell them at amazing speed. Even if you order them to kill you. So if you do happen to change your mind, it's very difficult to stop them from obeying the original order. [Stops computer from destroying Earth] But not impossible.", speaker: "The Fourth Doctor"},
    {quote: "Something's going on contrary to the laws of the universe. I must find out what!", speaker: "The Fourth Doctor"},
    {quote: "Deactivating a generator loop without the correct key is like repairing a watch with a hammer and chisel; one false move and you'll never know the time again.", speaker: "The Fourth Doctor"},
    {quote: "Excuse me, can you help me? I'm a spy.", speaker: "The Fourth Doctor"},
    {quote: "Yes, well, I can see your long rest hasn't done anything to cure your megalomania. Have a jelly baby.", speaker: "The Fourth Doctor"},
    {quote: "First things first, but not necessarily in that order.", speaker: "The Fourth Doctor"},
    
    {quote: "That's the trouble with regeneration. You quite never know what you're going to get.", speaker: "The Fifth Doctor"},
    {quote: "An apple a day keeps the... Ah, never mind.", speaker: "The Fifth Doctor"},
    {quote: "Oh, marvelous. You're going to kill me. What a finely tuned response to the situation.", speaker: "The Fourth Doctor"},
    {quote: "For some people, small, beautiful events are what life is all about!", speaker: "The Fifth Doctor"},
    {quote: "You know how it is; you put things off for a day and next thing you know, it's a hundred years later.", speaker: "The Fifth Doctor"},
    {quote: "Like Alice I try to believe three impossible things before breakfast!", speaker: "The Fifth Doctor"},
    {quote: "You may disguise your features but you can never disguise your intent.", speaker: "The Fifth Doctor"},
    
    {quote: "In all my travelling, I have battled against evil, against power-mad conspirators. I should have stayed here. The oldest civilization. Decadent, degenerate, and rotten to the core. Power-mad conspirators. Daleks, Sontarans, Cybermen. They're still in the nursery compared to us. Ten million years of absolute power. That's what it takes to become really corrupt.", speaker: "The Sixth Doctor"},
    {quote: "Planets come and go. Stars perish. Matter disperses, coalesces, forms into other patterns, other worlds. Nothing is eternal.", speaker: "The Sixth Doctor"},
    {quote: "Guns can seriously damage your health, you know.", speaker: "The Sixth Doctor"},
    {quote: "What's the use of a good quotation if you can't change it?", speaker: "The Sixth Doctor"},
    {quote: "What's he up to now? It'll be something devious and overcomplicated. He'd get dizzy if he tried to walk in a straight line.", speaker: "The Sixth Doctor"},
    {quote: "Oh, I thought you were my mirror image. Until I realized I wasn't the one holding a gun.", speaker: "The Sixth Doctor"},
    {quote: "Sorry about that, but we weren't getting anywhere with me playing pat-a-cake with the wall.", speaker: "The Sixth Doctor"},
    {quote: "That's three I's in one breath. Makes you sound a rather egotistical young lady.", speaker: "The Sixth Doctor"},
    {quote: "This is a situation that requires tact and finesse. Fortunately, I am blessed with both.", speaker: "The Sixth Doctor"},

    {quote: "You can always judge a man by the quality of his enemies.", speaker: "The Seventh Doctor"},
    {quote: "This may qualify as the worst miscalculation since life crawled out of the seas on this sad planet.", speaker: "The Seventh Doctor"},
    {quote: "All civilization starts with hunting and foraging, but don't worry. You'll soon work your way up.", speaker: "The Seventh Doctor"},
    {quote: "We all have a universe of our own terrors to face.", speaker: "The Seventh Doctor"},
    {quote: "There are worlds out there where the sky is burning, and the sea's asleep, and the rivers dream; people made of smoke and cities made of song. Somewhere there's danger, somewhere there's injustice, and somewhere else the tea's getting cold. Come on, Ace. We've got work to do.", speaker: "The Seventh Doctor"},
    {quote: "You don't understand regeneration, Mel. It's a lottery, and I've drawn the short plank.", speaker: "The Seventh Doctor"},
    {quote: "Your species has the most amazing capacity for self-deception, matched only by its ingenuity when trying to destroy itself.", speaker: "The Seventh Doctor"},
    
    {quote: "Now you’re going to tell me all about the other vampires here. How many of you, where you came from, anything you think I might be interested in. And then, if you’ll pardon the expression, you’re going to take me to your leader.", speaker: "The Eighth Doctor"},
    {quote: "It always amazes me how everything fits together. All the patterns that people would never suspect are there just to look at them. The way that atoms make up a molecule, molecules make up a protein, proteins make up a cell, cells make up people, people make up worlds. The tiniest interactions of these obscure little unrelated parts can change everything on levels you’d never dream of.", speaker: "The Eighth Doctor"},
    {quote: "I can't make your dream come true forever, but I can make it come true today.", speaker: "The Eighth Doctor"},
    {quote: "I love humans. Always seeing patterns in things that aren't there.", speaker: "The Eighth Doctor"},
    {quote: "Four minutes? That's ages. What if I get bored?", speaker: "The Eighth Doctor"},
    
    {quote: "Go back to your lives. Go and be the Doctor that I could never be.", speaker: "The War Doctor"},
    {quote: "What I did, I did without choice. In the name of peace and sanity", speaker: "The War Doctor"},
    {quote: "Great men are forged in fire. It is the privilege of lesser men to light the flame.", speaker: "The War Doctor"},
    {quote: "I don't suppose we will ever know if it succeeded, but at worst we failed doing the right thing, as opposed to succeeding and doing the wrong.", speaker: "The War Doctor"},
    {quote: "Why are you pointing your screwdrivers like that?  They’re scientific instruments, not water pistols!  You look like you’ve seen a ghost.", speaker: "The War Doctor"},
    {quote: "Oh, the pointing again.  They’re screwdrivers.  What are you going to do, assemble a cabinet at them?", speaker: "The War Doctor"},
    {quote: "So I won’t remember that I tried to save Gallifrey, rather than burn it.  And I have to live with that.  But for now, for this moment, I am the Doctor again.  Thank you.", speaker: "The War Doctor"},
    
    {quote: "Before I go, I just want to tell you, you were fantastic. Absolutely fantastic. And you know what? So was I.", speaker: "The Ninth Doctor"},
    {quote: "900 years of time and space, and I've never been slapped by someone's mother", speaker: "The Ninth Doctor"},
    {quote: "Time travel is like visiting Paris. You can't just read the guidebook; you've got to throw yourself in! Eat the food, use the wrong verbs, get charged double and end up kissing complete strangers!", speaker: "The Ninth Doctor"},
    {quote: "You think you know your own name? How stupid are you?", speaker: "The Ninth Doctor"},
    {quote: "And I'm looking for a blonde in a Union Jack. A specific one, mind, I didn't just wake up this morning with a craving", speaker: "The Ninth Doctor"},
    {quote: 'You\'re happy to believe in something that\'s invisible but if it\'s staring you in the face..."Nope! Can\'t see it."', speaker: "The Ninth Doctor"},
    {quote: "You lot. You spend all your time thinking about dying, like you're going to get killed by eggs or beef, or global warming, or asteroids. But you never take time to imagine the impossible.", speaker: "The Ninth Doctor"},
    {quote: "There's one thing you're forgetting. I'm the Doctor, and if there's one thing I can do it's talk. I have five billion languages and there's nothing you can do to stop me, so if anyone's going to shut up, it's you!", speaker: "The Ninth Doctor"},
    {quote: "I'm glad that worked, those would have been terrible last words.", speaker: "The Ninth Doctor"},
    
    
    {quote: "I can still die. If I'm killed before regeneration, then I'm dead. Even then, even if I change, it feels like dying. Everything I am dies. Some new man goes sauntering away... and I'm dead.", speaker: "The Tenth Doctor"},
    {quote: "It's not that I'm an innocent. I've taken lives. I got worse, I got clever. Manipulated people into taking their own. Sometimes, I think a Time Lord lives too long...", speaker: "The Tenth Doctor"},
    {quote: 'You need to get yourself a better dictionary. When you do, look up "genocide". You\'ll find a little picture of me there, and the caption\'ll read "Over my dead body".', speaker: "The Tenth Doctor"},
    {quote: "There’s no one to turn to. Because who’s gonna believe the things you see out of the corner of your eye? No one. Except me.", speaker: "The Tenth Doctor"},
    {quote: "That’s what I am: just a traveler. Imagine it: no tax, no bills, no boss. Just the open sky.", speaker: "The Tenth Doctor"},
    {quote: "People assume that time is a strict progression of cause to effect, but actually from a non-linear, non-subjective viewpoint, it’s more like a big ball of wibbly-wobbly, timey-wimey stuff.", speaker: "The Tenth Doctor"},
    {quote: "Tracked you down with this. This is my timey-wimey detector. It goes ding when there’s stuff. Also, it can boil an egg at 30 paces, whether you want it to or not, actually, so I’ve learned to stay away from hens. It’s not pretty when they blow.", speaker: "The Tenth Doctor"},
    {quote: "Don’t blink. Don’t even blink. Blink and you’re dead. They are fast. Faster than you can believe. Don’t turn your back, don’t look away, and DON’T blink.", speaker: "The Tenth Doctor"},
    {quote: "You want weapons? We’re in a library! Books! The best weapons in the world!", speaker: "The Tenth Doctor"},
    {quote: "Some people live more in 20 years than others do in 80. It’s not the time that matters, it’s the person.", speaker: "The Tenth Doctor"},
    {quote: "Everyone has nightmares; even big scary monsters from under the bed have nightmares", speaker: "The Tenth Doctor"},
    {quote: "Think you've seen it all? Think again. Outside those doors, we might see anything. We could find new worlds, terrifying monsters, impossible things. And if you come with me... nothing will ever be the same again!", speaker: "The Tenth Doctor"},
    {quote: "I know that one man can change the course of history. Right idea in the right place at the right time is all it takes. I've got to believe it's possible.", speaker: "The Tenth Doctor"},
    {quote: "I’m old enough to know that a longer life isn’t always a better one. In the end, you just get tired; tired of the struggle, tired of losing everyone that matters to you, tired of watching everything you love turn to dust. If you live long enough, Lazarus, the only certainty left is that you’ll end up alone.", speaker: "The Tenth Doctor"},
    
    {quote: "Bow ties are cool.", speaker: "The Eleventh Doctor"},
    {quote: "Legs! I've still got legs!! [kisses one of them.] Good. Arms, hands. Ooh, fingers. Lots of fingers. Ears? Yes. Eyes: two. Nose... eh, I've had worse. Chin - blimey! Hair... [notes length.] I'm a girl! [checks Adam's apple.] No! No! I'm not a girl! [pulls a lock of his hair in front of his eyes and looks at it, agitated] And still not ginger! There's something else. Something... important, I'm... [taps head.] I'm-I'm...", speaker: "The Eleventh Doctor"},
    {quote: "I don't age. I regenerate. But humans decay, you wither and you die. Imagine watching that happen to someone that you — YOU CAN SPEND THE REST OF YOUR LIFE WITH ME but I CAN'T SPEND THE REST OF MINE WITH YOU. I have to live on. Alone. That's the curse of the Time Lords.", speaker: "The Eleventh Doctor"},
    {quote: "All of time and space, everything that ever happened or ever will - where do you want to start?", speaker: "The Eleventh Doctor"},
    {quote: "What's the point in them being happy now if they're going to be sad later? The answer is, of course, because they are going to be sad later.", speaker: "The Eleventh Doctor"},
    {quote: "I am and always will be the optimist. The hoper of far-flung hopes and the dreamer of improbable dreams.", speaker: "The Eleventh Doctor"},
    {quote: "Every life is a pile of good things and bad things. The good things don’t always soften the bad things but, vice versa, the bad things don’t always spoil the good things and make them unimportant.", speaker: "The Eleventh Doctor"},
    {quote: 'Come on, look at me. No plan, no back up, no weapons worth a damn, oh, and something else I don’t have. Anything to lose! So, if you’re sitting up there in your silly little space ships with all your silly little guns, and you’ve got any plans on taking the Pandorica tonight, just remember who’s standing in your way! Remember every black day I ever stopped you, And then, do the smart thing! Let somebody else try first.', speaker: "The Eleventh Doctor"},  
    {quote: "In 900 years of time and space, I've never met anyone who wasn't important", speaker: "The Eleventh Doctor"},
    {quote: "Good men don't need rules. Today is not a good day to find out why I have so many.", speaker: "The Eleventh Doctor"},
    {quote: "My name, my real name, that is not the point. The name I chose is the Doctor. The name you choose, it's like, it's like a promise you make.", speaker: "The Eleventh Doctor"},
    {quote: "I have a new destination. My Journey is the same as yours. The same as anyone's. It's taken me so many years. So many lifetimes. But at last I know where I'm going. Where I've always been going. Home. The Long way around.", speaker: "The Eleventh Doctor"},
    {quote: "Carrots. Are you insane? No, wait. Hang on, I know what I need. I need… fish fingers. And custard.", speaker: "The Eleventh Doctor"},
    
    {quote: "Pain is a gift. Without the capacity for pain, we can't feel the hurt we inflict.", speaker: "The Twelfth Doctor"},
    {quote: "Sometimes the only choices you have are bad ones, but you still have to choose.", speaker: "The Twelfth Doctor"},
    {quote: "Could you not just let me enjoy this moment of not knowing something? I mean, it happens so rarely.", speaker: "The Twelfth Doctor"},
    {quote: "Never trust a hug, it's just a way to hide your face.", speaker: "The Twelfth Doctor"},
    {quote: "What's wrong with scared? Scared is a super power. It's your super power. There is danger in this room, and guess what? It's you! You feel it?", speaker: "The Twelfth Doctor"},
    {quote: "So you've got a whole room for not being awake in? But what's the point? You're just missing the room. And don't look in that mirror. It's absolutely furious.", speaker: "The Twelfth Doctor"},
    {quote: "The deep and lovely dark, you would never see the stars without it.", speaker: "The Twelfth Doctor"},
    {quote: "You can't see me, can you? You look at me and you can't see me. Do you have any idea what that's like? I'm not on the phone. I'm right here. Standing in front of you. Please. Just... Just see me.", speaker: "The Twelfth Doctor"},
    {quote: "I don't like being sure about things. One minute you're sure, the next, everyone turns into lizards and a piano falls on your head.", speaker: "The Twelfth Doctor"},
    {quote: "Never be cruel and never be cowardly. And if you ever are, always make amends.", speaker: "The Twelfth Doctor"},
    {quote: "This is your power source. And feeble though it is, I can use it to blow this whole room if I see one thing that I don't like. And that includes karaoke and mimes, so take no chances.", speaker: "The Twelfth Doctor"},
    {quote: "You want to know what's in that box? I'll tell you what's in that box! It's a Time Machine! It also travels in space! And it usually contains a man who just wants to get on with his work of preventing the end of the world — but keeps on getting interrupted by boring little humans!", speaker: "The Twelfth Doctor"},
    {quote: " I am not a good man! And I'm not a bad man either. I'm not a hero. I'm definitely not a president, and no, I'm not an officer. You know who I am? I… am… an idiot! With a box and a screwdriver. Passing through. Helping out. Learning. I don't need an army. I never have. Because I've got them, always them, because love is not an emotion.", speaker: "The Twelfth Doctor"},
    {quote: "Your chances of survival are about one in a thousand. So here's what you do. You forget the thousand, and you concentrate on the one.", speaker: "The Twelfth Doctor"},
    {quote: " Listen to me. Listen. I just… I just want you to think. Do you know what thinking is? It's just a fancy word for changing your mind!", speaker: "The Twelfth Doctor"},
    {quote: "I can do whatever the hell I like. You read the stories. You know who I am! And in all that time, did you ever hear anything about anyone who stopped me?", speaker: "The Twelfth Doctor"},
]